apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: news-aggregator-infra
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  url: https://github.com/gt005/news_aggregator_infra.git
  secretRef:
    name: git-credentials
