apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageUpdateAutomation
metadata:
  name: staging
spec:
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: news-aggregator-infra
    namespace: flux-system
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        email: fluxcd[bot]@users.noreply.github.com
        name: fluxcd[bot]
      messageTemplate: "{{range .Updated.Images}}{{println .}}{{end}}"
    push:
      branch: main
  update:
    path: /apps
    strategy: Setters
  secretRef:
    name: git-credentials
