apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
  - apps/postgres
  - apps/redis
  - apps/backend
  - apps/frontend
  - apps/website-parsing-service
  - apps/parser-telegram
  - apps/backend-news-data-processor
  - ingress.yaml
