apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml

secretGenerator:
  - name: frontend-secrets
    envs:
      - secrets.enc.yaml
configMapGenerator:
  - name: frontend-config
    envs:
      - configmaps.env

generatorOptions:
  disableNameSuffixHash: true
