apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
spec:
  selector:
    app: frontend
  type: ClusterIP
  ports:
    - port: 5173
      targetPort: 5173
      protocol: TCP
      name: http
