apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-backend
  labels:
    app: fastapi-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi-backend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: fastapi-backend
    spec:
      containers:
      - name: fastapi-backend
        image: gt005/news_aggregator_fastapi_backend:db071a03bc86c467b6738c9257b2ed4033800cd9
        envFrom:
          - configMapRef:
              name: backend-config
          - secretRef:
              name: backend-secrets
        ports:
          - name: http
            containerPort: 8000
            protocol: TCP
