apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
  - deployment.yaml
  - service.yaml
  - migrate-job.yaml

configMapGenerator:
  - name: backend-config
    envs:
      - configmaps.env

secretGenerator:
  - name: backend-secrets
    files:
      - secrets.enc.yaml
    options:
      disableNameSuffixHash: true

transformers:
  - secret-transformer.yaml

generatorOptions:
  disableNameSuffixHash: true
