apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
  - deployment.yaml
  - service.yaml
  - migrate-job.yaml
  - secrets.enc.yaml

configMapGenerator:
  - name: backend-config
    envs:
      - configmaps.env

generatorOptions:
  disableNameSuffixHash: true
