apiVersion: batch/v1
kind: Job
metadata:
  name: backend-migrate
spec:
  backoffLimit: 1
  template:
    spec:
      restartPolicy: Never
      imagePullSecrets:
        - name: regcred
      automountServiceAccountToken: false
      containers:
        - name: fastapi-backend
          image: gt005/news_aggregator_fastapi_backend:60f0b711b46ae2bb54c3c7fe84c211f0db2eb512
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: backend-secrets
            - secretRef:
                name: backend-secrets
          command: ["bash", "-c", "alembic upgrade heads"]
          resources:
            requests:
              ephemeral-storage: "512Mi"
            limits:
              ephemeral-storage: "1024Mi"
