apiVersion: v1
kind: Service
metadata:
  name: fastapi-backend-svc
spec:
  selector:
    app: fastapi-backend
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: http
