apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml

secretGenerator:
  - name: parser-telegram-secrets
    envs:
      - secrets.enc.yaml
configMapGenerator:
  - name: parser-telegram-config
    envs:
      - configmaps.env

generatorOptions:
  disableNameSuffixHash: true
