apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-news-data-processor
  labels:
    app: backend-news-data-processor
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend-news-data-processor
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: backend-news-data-processor
    spec:
      containers:
      - name: backend-news-data-processor
        image: gt005/news_aggregator_backend_data_processor:60f0b711b46ae2bb54c3c7fe84c211f0db2eb512
        ports:
          - containerPort: 8002
        envFrom:
          - secretRef:
              name: backend-data-processor-secrets
          - configMapRef:
              name: backend-data-processor-config
