apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
  - deployment.yaml
  - service.yaml
  - image-automation/image-repository.yaml
  - image-automation/image-policy.yaml
  - image-automation/image-update-automation.yaml

configMapGenerator:
  - name: backend-data-processor-config
    envs:
      - configmaps.env

generatorOptions:
  disableNameSuffixHash: true
