apiVersion: v1
kind: Service
metadata:
  name: backend-news-data-processor-svc
spec:
  selector:
    app: backend-news-data-processor
  type: ClusterIP
  ports:
    - port: 8002
      targetPort: 8002
      protocol: TCP
      name: http
