apiVersion: apps/v1
kind: Deployment
metadata:
  name: website-parsing-service

  labels:
    app: website-parsing-service

spec:
  replicas: 1
  selector:
    matchLabels:
      app: website-parsing-service
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: website-parsing-service
    spec:
      containers:
      - name: website-parsing-service
        image: gt005/news_aggregator_website_parser:f4b02d74073c7c67dafac0a19d9a7f1d4c852fa7
