apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml

secretGenerator:
  - name: website-parsing-service-secrets
    envs:
      - secrets.enc.yaml
configMapGenerator:
  - name: website-parsing-service-config
    envs:
      - configmaps.env

generatorOptions:
  disableNameSuffixHash: true
