apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: frontend
spec:
  imageRepositoryRef:
    name: frontend
  filterTags:
    pattern: "^(?P<commit>[a-f0-9]{40})$"
    extract: "$commit"
  policy:
    numerical:
      order: asc
