apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgres
  namespace: default
spec:
  releaseName: postgres
  chart:
    spec:
      chart: postgresql
      sourceRef:
        kind: HelmRepository
        name: bitnami
      version: 12.5.6
  interval: 10m0s
  timeout: 5m0s
  values:
    fullnameOverride: postgres
    image:
      registry: mirror.gcr.io
      repository: bitnami/postgresql
      tag: 15.3.0
    auth:
      username: newsFusion
      database: apiServiceDb
      existingSecret: postgres
    primary:
      resources:
        requests:
          cpu: 128m
          memory: 256Mi
          ephemeral-storage: 512Mi
        limits:
          cpu: 256m
          memory: 512Mi
          ephemeral-storage: 1Gi
      persistence:
        accessModes:
          - ReadWriteOnce
        size: 3Gi
    primary:
      extraEnv:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secrets
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secrets
              key: POSTGRES_PASSWORD
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: postgres-secrets
              key: POSTGRES_DB
