apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: website-parsing-service
spec:
  imageRepositoryRef:
    name: website-parsing-service
  filterTags:
    pattern: "^(?P<commit>[a-f0-9]{40})$"
    extract: "$commit"
  policy:
    numerical:
      order: asc
