apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: redis
  namespace: default
spec:
  releaseName: redis
  chart:
    spec:
      chart: redis
      sourceRef:
        kind: HelmRepository
        name: default
      version: 16.6.0
  interval: 24h
  values:
    fullnameOverride: redis
    architecture: standalone
    master:
      persistence:
        size: 1Gi
    auth:
      enabled: false
