apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: backend
spec:
  imageRepositoryRef:
    name: backend
  filterTags:
    pattern: "^(?P<commit>[a-f0-9]{40})$"
    extract: "$commit"
  policy:
    numerical:
      order: asc
